export const REGISTER_FOR_EVENT = "REGISTER_FOR_EVENT";
export const REGISTER_FOR_EVENT_SUCCESS = "REGISTER_FOR_EVENT_SUCCESS";
export const REGISTER_FOR_EVENT_FAILED = "REGISTER_FOR_EVENT_FAILED";



